UPDATE visas SET ds160 = 'AA00FA13DL', estado = 'PAUSADA', notas = 'no contesta', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0004');
UPDATE visas SET ds160 = 'AA00FB7ANB', email_portal = 'costillasimon449@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0005');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, '$imontobiaS2001*' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0005' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FBMZ8D', email_portal = 'davidcostilla.98@gmail.com', notas = 'inicio 2018', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0006');
UPDATE visas SET ds160 = 'AA00FB8JJZ', email_portal = 'agushernandez666@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0007');
UPDATE visas SET ds160 = 'AA00F9RVJ3', email_portal = 'Matiasruiz327327@gmail.com', notas = 'inicio 2013', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0008');
UPDATE visas SET ds160 = 'AA00FCJGEX', email_portal = 'Martinadiaz22mx@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0009');
UPDATE visas SET ds160 = 'AA00F9KB5B', email_portal = 'alelopez2832@gmail.com', notas = 'inicio 2015', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0010');
UPDATE visas SET ds160 = 'AA00FCF2LB', email_portal = 'camiamado13@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0011');
UPDATE visas SET ds160 = 'AA00F9VCIB', email_portal = 'tabaresgonzalo3@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0012');
UPDATE visas SET ds160 = 'AA00FBB02X', email_portal = 'gasparjh@gmail.com', notas = 'inicio oct 2023', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0013');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Leonardosuarez1997.' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0013' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FBT03R', email_portal = 'josefinajara598@gmail.com', notas = 'inicio 2023', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0014');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Josefinetajara02#' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0014' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FBMLGP', email_portal = 'younisyasintop@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0015');
UPDATE visas SET ds160 = 'AA00FBSX7N', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0016');
UPDATE visas SET ds160 = 'AA00FBST4Z', email_portal = 'danielinigo38@icloud.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0017');
UPDATE visas SET ds160 = 'AA00FBSYBX', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0018');
UPDATE visas SET ds160 = 'AA00FCF0XL', email_portal = 'agosaylens@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0019');
UPDATE visas SET ds160 = 'AA00FB7FT9', email_portal = 'Santinoviera860@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0020');
UPDATE visas SET ds160 = 'AA00FC1E0V', email_portal = 'luke2508@hotmail.com', notas = 'Desarrollo, optimizacion y administracion de software orientado a ciberseguridad 2024', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0023');
UPDATE visas SET ds160 = 'AA00FCJ7DR', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0024');
UPDATE visas SET ds160 = 'AA00FCDW9R', email_portal = 'marianocolomo95@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0025');
UPDATE visas SET ds160 = 'AA00FCD51F', email_portal = 'nachitomozeluk@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0026');
UPDATE visas SET ds160 = 'AA00FCW5XN', email_portal = 'Leticiaaagimenez@gmail.com', estado = 'APROBADA', notas = 'inicio 2023', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0027');
UPDATE visas SET ds160 = 'AA00FCWAGF', email_portal = 'Ignaciofacee@gmail.com', notas = 'inicio 2024', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0028');
UPDATE visas SET ds160 = 'AA00FD96PD', email_portal = 'farid97leskano@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0029');
UPDATE visas SET ds160 = 'AA00FCVETJ', email_portal = 'tom29can@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0031');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'rytQuv-netzup-gofwe1' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0031' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FDEKXJ', email_portal = 'elianmayocchi02@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0032');
UPDATE visas SET ds160 = 'AA00FE34J9', email_portal = 'sofiabelenf23@gmail.com', estado = 'PAUSADA', notas = 'esperar nov', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0033');
UPDATE visas SET ds160 = 'AA00FDHQKR', email_portal = 'leandro.tello.98@pomelo.lemonzana.lol', estado = 'APROBADA', notas = 'inicio 2023', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0035');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'g3n3r4ls' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0035' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FDF0UT', email_portal = 'milagrosvlescano01@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0036');
UPDATE visas SET email_portal = 'jeremiasnale4@gmail.com', notas = 'inicio 2024', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0037');
UPDATE visas SET ds160 = 'AA00FDHO6T', email_portal = 'belendami571@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0038');
UPDATE visas SET ds160 = 'AA00FDONC1', email_portal = 'Gonzalezcandelaria92@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0040');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Cande_74visa2026' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0040' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FDXIYZ', email_portal = 'braiandes13@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0041');
UPDATE visas SET ds160 = 'AA00FE2RCL', email_portal = 'maraaybar15@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0042');
UPDATE visas SET email_portal = 'ernestoavalo75@gmail.com', estado = 'PAUSADA', notas = 'esperar dinero', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0043');
UPDATE visas SET ds160 = 'AA00FDKUSF', email_portal = 'Agustinporelmundo@icloud.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0046');
UPDATE visas SET ds160 = 'AA00FE2YRZ', email_portal = 'jeroquiroga1@hotmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0048');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Leonardosuarez1997.' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0048' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FECT6D', email_portal = 'vivianamerlinapaz@gmail.com', notas = 'inicio 2024', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0049');
UPDATE visas SET ds160 = 'AA00FEJFZZ', notas = 'inicio 2021', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0050');
UPDATE visas SET ds160 = 'AA00FENEED', email_portal = 'nadiaaenria@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0051');
UPDATE visas SET ds160 = 'AA00FETYUR', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0052');
UPDATE visas SET ds160 = 'AA00FF2ULR', email_portal = 'mariquenalopez94@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0054');
UPDATE visas SET ds160 = 'AA00FF30SZ', email_portal = 'bdavito31@gmail.com', estado = 'APROBADA', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0055');
UPDATE visas SET ds160 = 'AA00FFV9YP', email_portal = 'francoaragon842@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0057');
UPDATE visas SET ds160 = 'AA00FFNS7N', email_portal = 'betianapioli@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0058');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Betiana19170501++' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0058' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FG8VJT', email_portal = 'francosromano.1994@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0059');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Greglaferrere3001!' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0059' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FG8Z0N', email_portal = 'gonzalojesusbarilari@hotmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0063');
INSERT INTO credenciales (visa_id, password_portal) SELECT v.id, 'Barilarilaprida@221' FROM visas v JOIN clientes c ON c.id = v.cliente_id WHERE c.gj_id = 'GJ-0063' ON CONFLICT (visa_id) DO UPDATE SET password_portal = EXCLUDED.password_portal;
UPDATE visas SET ds160 = 'AA00FGR1TF', email_portal = 'bernabeapm@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0065');
UPDATE visas SET ds160 = 'AA00FGCW2J', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0066');
UPDATE visas SET ds160 = 'AA00FGFBNF', email_portal = 'Ljst380@gmail.com', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0067');
UPDATE visas SET ds160 = 'AA00FGUV99', email_portal = 'danielfiat_@hotmail.com', notas = 'inicio 2009', updated_at = now() WHERE cliente_id = (SELECT id FROM clientes WHERE gj_id = 'GJ-0068');